In [2]:
import numpy as np

In [5]:
a=np.array([[1,2],[2,3]])

In [8]:
a @ a

array([[ 5,  8],
       [ 8, 13]])

In [9]:
a.T

array([[1, 2],
       [2, 3]])

In [10]:
a.T

array([[1, 2],
       [2, 3]])

In [14]:
a.__dir__()

['__repr__',
 '__hash__',
 '__str__',
 '__lt__',
 '__le__',
 '__eq__',
 '__ne__',
 '__gt__',
 '__ge__',
 '__iter__',
 '__add__',
 '__radd__',
 '__sub__',
 '__rsub__',
 '__mul__',
 '__rmul__',
 '__mod__',
 '__rmod__',
 '__divmod__',
 '__rdivmod__',
 '__pow__',
 '__rpow__',
 '__neg__',
 '__pos__',
 '__abs__',
 '__bool__',
 '__invert__',
 '__lshift__',
 '__rlshift__',
 '__rshift__',
 '__rrshift__',
 '__and__',
 '__rand__',
 '__xor__',
 '__rxor__',
 '__or__',
 '__ror__',
 '__int__',
 '__float__',
 '__iadd__',
 '__isub__',
 '__imul__',
 '__imod__',
 '__ipow__',
 '__ilshift__',
 '__irshift__',
 '__iand__',
 '__ixor__',
 '__ior__',
 '__floordiv__',
 '__rfloordiv__',
 '__truediv__',
 '__rtruediv__',
 '__ifloordiv__',
 '__itruediv__',
 '__index__',
 '__matmul__',
 '__rmatmul__',
 '__imatmul__',
 '__len__',
 '__getitem__',
 '__setitem__',
 '__delitem__',
 '__contains__',
 '__new__',
 '__array__',
 '__array_prepare__',
 '__array_wrap__',
 '__array_ufunc__',
 '__sizeof__',
 '__copy__',
 '__deepcop

In [15]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square) 

{0: 0, 2: 4, 4: 16}


In [16]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums)  # Prints "{0, 1, 2, 3, 4, 5}"

{0, 1, 2, 3, 4, 5}


In [17]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)        # Create a tuple
print(type(t))    # Prints "<class 'tuple'>"
print(d[t])       # Prints "5"
print(d[(1, 2)])  # Prints "1"

<class 'tuple'>
5
1


In [18]:
d

{(0, 1): 0,
 (1, 2): 1,
 (2, 3): 2,
 (3, 4): 3,
 (4, 5): 4,
 (5, 6): 5,
 (6, 7): 6,
 (7, 8): 7,
 (8, 9): 8,
 (9, 10): 9}

In [19]:
v = np.array([1,2,3])

In [20]:
v @ v

14

In [21]:
v @ v.T

14

In [23]:
v.T @ v

14

In [24]:
v.dot(v)

14

In [25]:
v.dot(v.T)

14

In [26]:
v.shape

(3,)

In [31]:
np.shape(v.reshape((3,1)))

(3, 1)

In [30]:
v.shape

(3,)

In [32]:
np.shape(v.reshape((1,3)))

(1, 3)

In [33]:
v.reshape((1,3))

array([[1, 2, 3]])

In [34]:
w = v.reshape((3,1))

In [35]:
v*w

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [36]:
v+w

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [37]:
v+w/2

array([[ 1.5,  2.5,  3.5],
       [ 2. ,  3. ,  4. ],
       [ 2.5,  3.5,  4.5]])

In [38]:
v

array([1, 2, 3])

In [40]:
v + v.T

array([2, 4, 6])

[![Geometry](http://i3.ytimg.com/vi/OkmNXy7er84/hqdefault.jpg)](https://www.youtube.com/watch?v=OkmNXy7er84 "3Blue1Brown Geometry")

In [41]:
z = v

In [42]:
z

array([1, 2, 3])

In [43]:
z[1] = 3

In [44]:
v

array([1, 3, 3])

In [48]:
z = np.copy(v)

In [50]:
z[1] = 4

In [51]:
z

array([1, 4, 3])

In [52]:
v

array([1, 3, 3])

In [60]:
a = np.array([[20,0,0],[0,4,0],[0,0,1]])

In [61]:
a

array([[20,  0,  0],
       [ 0,  4,  0],
       [ 0,  0,  1]])

In [62]:
np.linalg.cond(a)

20.0